camel:
  springboot:
    name: camel-context-telao-interativo-sptv

spring:
    application:
        name: telao-interativo-sptv
    main:
        banner-mode: "off"
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop
    h2:
        console:
            enabled: true
            path: /h2            
    security:
        enabled: false        

camel.component.twitter.consumer-key: YOUR-CONSUMER-KEY
camel.component.twitter.consumer-secret: YOUR-CONSUMER-SECRET
camel.component.twitter.access-token: YOUR-ACCESS-TOKEN
camel.component.twitter.access-token-secret: YOUR-ACESS-TOKEN-SECRET

custom.twitter.delay-each-request: 6000
custom.twitter.keywords: "#SP1"

custom.scheduler.delay-each-read: 10000

custom.brokerURL: tcp://localhost:61616?jms.prefetchPolicy.all=1

custom.websocket-port: 8095

---

spring:
    profiles: it
    
custom.brokerURL: tcp://localhost:${activemq.port}?jms.prefetchPolicy.all=1    